# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$character\
"""
# $line_break\

right_format = """
$status\
"""

add_newline = false

[character]
success_symbol = "[➜](bold white)"
error_symbol = "[➜](bold red)"

[directory]
style = "bold white"
format = "[$path]($style) "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_commit]
style = "bold purple"

[hostname]
ssh_symbol = "@"
format = "[$ssh_symbol$hostname]($style) "
style = "blue dimmed bold"

[status]
disabled = false
# symbol = ""
# symbol = ""
# symbol = ""
symbol = ""
format = "[$symbol $status]($style)"
style = "dimmed bold red"

[username]
format = "[$user]($style) "
style_user = "yellow bold"
